### ISSUE TITLE
curl 4.1 is failing to compile on RHEL 7

### ISSUE THREAD

**Issue by mjsteinbaugh** [jeroen/curl#204]
Hi @jeroen,

I'm hitting a new compilation issue related to `curl_sslbackend` with curl 4.1 on my Azure VMs running RHEL 7. curl v4.0 installs fine on these VMs. Here's the install log:

```r
install.packages("curl")
```

```
trying URL 'https://cloud.r-project.org/src/contrib/curl_4.1.tar.gz'
Content type 'application/x-gzip' length 667788 bytes (652 KB)
==================================================
downloaded 652 KB

* installing *source* package ‘curl’ ...
** package ‘curl’ successfully unpacked and MD5 sums checked
** using staged installation
Found pkg-config cflags and libs!
Using PKG_CFLAGS=
Using PKG_LIBS=-lcurl
** libs
rm -f curl.so callbacks.o curl.o download.o escape.o fetch.o form.o getdate.o handle.o ieproxy.o init.o interrupt.o multi.o nslookup.o reflist.o split.o ssl.o typechecking.o utils.o version.o winidn.o writer.o
gcc -std=gnu99 -I"/usr/local/lib64/R/include" -DNDEBUG -DSTRICT _R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c callbacks.c -o callbacks.o
gcc -std=gnu99 -I"/usr/local/lib64/R/include" -DNDEBUG -DSTRICT _R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c curl.c -o curl.o
gcc -std=gnu99 -I"/usr/local/lib64/R/include" -DNDEBUG -DSTRICT _R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c download.c -o download.o
gcc -std=gnu99 -I"/usr/local/lib64/R/include" -DNDEBUG -DSTRICT _R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c escape.c -o escape.o
gcc -std=gnu99 -I"/usr/local/lib64/R/include" -DNDEBUG -DSTRICT _R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c fetch.c -o fetch.o
gcc -std=gnu99 -I"/usr/local/lib64/R/include" -DNDEBUG -DSTRICT _R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c form.c -o form.o
gcc -std=gnu99 -I"/usr/local/lib64/R/include" -DNDEBUG -DSTRICT _R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c getdate.c -o getdate.o
gcc -std=gnu99 -I"/usr/local/lib64/R/include" -DNDEBUG -DSTRICT _R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c handle.c -o handle.o
handle.c:30:1: error: unknown type name ‘curl_sslbackend’
 curl_sslbackend default_ssl_backend;
 ^
make: *** [handle.o] Error 1
ERROR: compilation failed for package ‘curl’
* removing ‘/data00/R/site-library/3.6/curl’
* restoring previous ‘/data00/R/site-library/3.6/curl’
Warning in install.packages(update[instlib == l, "Package"], l, contriburl = contrib                    url,  :
  installation of package ‘curl’ had non-zero exit status
Calls: <Anonymous> ... .install_update -> update.packages -> install.packages

The downloaded source packages are in
        ‘/tmp/RtmpvupVyG/downloaded_packages’
```

Best,
Mike

**Comment by mjsteinbaugh** [comment]
To follow-up, I just double checked that this works on Azure RHEL 7, so it's a curl 4.1-specific issue:

```sh
wget https://cran.r-project.org/src/contrib/Archive/curl/curl_4.0.tar.gz
R CMD INSTALL curl_4.0.tar.gz
```

**Comment by mjsteinbaugh** [comment]
`libcurl` on these machines is from `sudo apt-get install -y libcurl-dev`, as recommended.

**Comment by amir-barkal** [comment]
I can confirm this is also affecting us on CentOS / RHEL 7.x
R version 3.3.1 (2016-06-21)

```
$ Rscript -e 'devtools::install_version(package = "curl", version = "4.1", repos = "https://cran.r-project.org/")'
Downloading package from url: https://cran.r-project.org/src/contrib/curl_4.1.tar.gz
* installing *source* package 'curl' ...
** package 'curl' successfully unpacked and MD5 sums checked
Found pkg-config cflags and libs!
Using PKG_CFLAGS= 
Using PKG_LIBS=-lcurl  
** libs
rm -f curl.so callbacks.o curl.o download.o escape.o fetch.o form.o getdate.o handle.o ieproxy.o init.o interrupt.o multi.o nslookup.o reflist.o split.o ssl.o typechecking.o utils.o version.o winidn.o writer.o
gcc -std=gnu99 -I/usr/local/lib64/R/include -DNDEBUG -DSTRICT_R_HEADERS -I/usr/local/include   -fvisibility=hidden -fpic  -g -O2  -c callbacks.c -o callbacks.o
gcc -std=gnu99 -I/usr/local/lib64/R/include -DNDEBUG -DSTRICT_R_HEADERS -I/usr/local/include   -fvisibility=hidden -fpic  -g -O2  -c curl.c -o curl.o
gcc -std=gnu99 -I/usr/local/lib64/R/include -DNDEBUG -DSTRICT_R_HEADERS -I/usr/local/include   -fvisibility=hidden -fpic  -g -O2  -c download.c -o download.o
gcc -std=gnu99 -I/usr/local/lib64/R/include -DNDEBUG -DSTRICT_R_HEADERS -I/usr/local/include   -fvisibility=hidden -fpic  -g -O2  -c escape.c -o escape.o
gcc -std=gnu99 -I/usr/local/lib64/R/include -DNDEBUG -DSTRICT_R_HEADERS -I/usr/local/include   -fvisibility=hidden -fpic  -g -O2  -c fetch.c -o fetch.o
gcc -std=gnu99 -I/usr/local/lib64/R/include -DNDEBUG -DSTRICT_R_HEADERS -I/usr/local/include   -fvisibility=hidden -fpic  -g -O2  -c form.c -o form.o
gcc -std=gnu99 -I/usr/local/lib64/R/include -DNDEBUG -DSTRICT_R_HEADERS -I/usr/local/include   -fvisibility=hidden -fpic  -g -O2  -c getdate.c -o getdate.o
gcc -std=gnu99 -I/usr/local/lib64/R/include -DNDEBUG -DSTRICT_R_HEADERS -I/usr/local/include   -fvisibility=hidden -fpic  -g -O2  -c handle.c -o handle.o
handle.c:30:1: error: unknown type name 'curl_sslbackend'
 curl_sslbackend default_ssl_backend;
 ^
make: *** [handle.o] Error 1
ERROR: compilation failed for package 'curl'
* removing '/usr/local/lib64/R/library/curl'
* restoring previous '/usr/local/lib64/R/library/curl'
Error: Failed to install 'unknown package' from URL:
  (converted from warning) installation of package '/tmp/Rtmpt75gLI/remotesf3706c9b2/curl' had non-zero exit status
Execution halted
```

**Comment by jeroen** [comment]
Sorry about this. Will fix asap.

**Comment by mjsteinbaugh** [comment]
No worries, just wanted to give you a heads up since RHEL / CentOS 7 is still pretty common on research clusters.

**Comment by telecodani** [comment]
I'm on the same situation on RHEL 7.5 and R version 3.6.0 (2019-04-26). I will use the previous version for now to continue. The oficial repositories still offer the last version 4.1 so I had to install from archive: `install.packages("https://cran.r-project.org/src/contrib/Archive/curl/curl_4.0.tar.gz",repo=NULL,type="source").`

**Comment by zillurbmb51** [comment]
I am also having the same problem in RHEL 7.5 and R3.6.0. I couldn't install any package on rstudio server in browser but could install in the commandline using sudo. The solution from @telecodani resolved part of the problems (After using this tip I could install some packages). Again I stuck in installing 'rjson'. I also tried  install.packages('https://cran.rstudio.com/src/contrib/rjson_0.2.20.tar.gz', repos = NULL, type='source') but nothing happened. Any help? Best, Zillur

**Comment by aronatkins** [comment]
CentOS6 (close to RHEL 6) with R 3.5.2 is hitting an error on the same line:

```
handle.c:30: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'default_ssl_backend'
```

CentOS7 (close to RHEL 7) with R 3.6.0 hits the `curl_sslbackend` error originally reported in this issue.

Pinning to curl-4.0 is a workaround for these platforms, as well.

**Comment by hanyunfan** [comment]
> @josephtate
Revert "Temporarily lock to curl version 4.0 because 4.1 is broken

I don't think the lock is working. 

[root@deepdell2 R_source]# R -e "install.packages('curl', repos = 'http://cloud.r-project.org/', lib='/cm/shared/apps/R_libs')"

R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-redhat-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages('curl', repos = 'http://cloud.r-project.org/', lib='/cm/shared/apps/R_libs')
trying URL 'http://cloud.r-project.org/src/contrib/curl_4.1.tar.gz'
Content type 'application/x-gzip' length 667788 bytes (652 KB)
==================================================
downloaded 652 KB

* installing *source* package ‘curl’ ...
** package ‘curl’ successfully unpacked and MD5 sums checked
** using staged installation
Found pkg-config cflags and libs!
Using PKG_CFLAGS=
Using PKG_LIBS=-lcurl
** libs
rm -f curl.so callbacks.o curl.o download.o escape.o fetch.o form.o getdate.o handle.o ieproxy.o init.o interrupt.o multi.o nslookup.o reflist.o split.o ssl.o typechecking.o utils.o version.o winidn.o writer.o
gcc -m64 -std=gnu99 -I"/usr/include/R" -DNDEBUG -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c callbacks.c -o callbacks.o
gcc -m64 -std=gnu99 -I"/usr/include/R" -DNDEBUG -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c curl.c -o curl.o
gcc -m64 -std=gnu99 -I"/usr/include/R" -DNDEBUG -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c download.c -o download.o
gcc -m64 -std=gnu99 -I"/usr/include/R" -DNDEBUG -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c escape.c -o escape.o
gcc -m64 -std=gnu99 -I"/usr/include/R" -DNDEBUG -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c fetch.c -o fetch.o
gcc -m64 -std=gnu99 -I"/usr/include/R" -DNDEBUG -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c form.c -o form.o
gcc -m64 -std=gnu99 -I"/usr/include/R" -DNDEBUG -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c getdate.c -o getdate.o
gcc -m64 -std=gnu99 -I"/usr/include/R" -DNDEBUG -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c handle.c -o handle.o
handle.c:30:1: error: unknown type name ‘curl_sslbackend’
 curl_sslbackend default_ssl_backend;
 ^
make: *** [handle.o] Error 1
ERROR: compilation failed for package ‘curl’
* removing ‘/cm/shared/apps/R_libs/curl’

The downloaded source packages are in
        ‘/tmp/RtmpJC75Xm/downloaded_packages’
Warning message:
In install.packages("curl", repos = "http://cloud.r-project.org/",  :
  installation of package ‘curl’ had non-zero exit status
>
>
[root@deepdell2 R_source]#

**Comment by ParsaAkbari** [comment]
I have the same issue which is preventing installation of any R package with a dependency on curl (R 3.5.0, Scientific Linux 7.6 Nitrogen).

**Comment by lculibrk** [comment]
Same issue:
R version 3.5.1 (2018-07-02)
Platform: x86_64-centos7-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

**Comment by jolson787** [comment]
Same issue:
R version: 3.4.4 (Oracle Distribution)
Platform: Linux 3.10.0-957.21.3.el7.x86_64 x86_64
Running under: Oracle Linux Server release 7.6

`
handle.c:30:1: error: unknown type name ‘curl_sslbackend’
 curl_sslbackend default_ssl_backend;
 ^
make: *** [handle.o] Error 1
ERROR: compilation failed for package ‘curl’
`

**Comment by ADGM** [comment]
Same issue:
R version 3.5.0 (2018-04-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

```
handle.c:30:1: error: unknown type name ‘curl_sslbackend’
 curl_sslbackend default_ssl_backend;
 ^
make: *** [handle.o] Error 1
ERROR: compilation failed for package ‘curl’
```

**Comment by dongxuzheng** [comment]
I got the same issue:
R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Platform: Linux version 3.10.0-957.el7.x86_64
Running under: CentOS Linux release 7.6.1810 (Core)

`handle.c:30:1: error: unknown type name ‘curl_sslbackend’
 curl_sslbackend default_ssl_backend;
 ^
make: *** [handle.o] Error 1
ERROR: compilation failed for package ‘curl’`

**Comment by johanneswaage** [comment]
Same issue, RHEL 7.6, R 3.5.1

**Comment by Neato-Nick** [comment]
Same issue, R 3.6.1 on CentOS. The workaround @telecodani suggested worked.

**Comment by kenahoo** [comment]
@jeroen , can you comment on the nature of the issue?  Was the `curl_sslbackend` type added or removed in some version of Curl, or something?

I also note that in CentOS 7 and RHEL 7, the version of `curl` seems to be 7.29.0, released in February 2013, which seems kind of insanely old.

**Comment by jeroen** [comment]
I will try to fix this over the weekend.

The issue is silly, that I use a type (mostly for windows) which was introduced in curl a few years ago. So thereby unintentionally the minimal version of libcurl is now higher than the one in CentOS.

I didn't intend this, I just need to condition some stuff on a minimal version of libcurl.

**Comment by amir-barkal** [comment]
Anything we can do to help with this fix?
Thanks!

**Comment by jeroen** [comment]
>Anything we can do to help with this fix?

Yes you can make a [donation to WWF](https://www.worldwildlife.org/donate/). Each donation will push this issue higher in priority :)

**Comment by hanyunfan** [comment]
@jeroen Thanks for the fix, but just tried I still have this issue. As I am still downloading the 4.1 version, anything I need to do to clear the cache?

"trying URL 'http://cloud.r-project.org/src/contrib/curl_4.1.tar.gz'"

**Comment by Eli-Berkow** [comment]
The fix is in 4.1.1 which is not yet on CRAN. Use `install.packages("https://github.com/jeroen/curl/archive/master.tar.gz",` repos = NULL)` for now

**Comment by hanyunfan** [comment]
> @hanyunfan The fix is in 4.1.1 which is not yet on CRAN. Use `install.packages("https://github.com/jeroen/curl/archive/master.tar.gz", repos = NULL)` for now.

Thanks a lot.

Any idea how soon it can be on CRAN? Curl is a package in the chain packages of my script. I'd rather wait for a couple of days if it can be merged on CRAN soon.

**Comment by mjsteinbaugh** [comment]
Thanks @jeroen !

**Comment by zillurbmb51** [comment]
Hello there, I have tried all the commands mentioned here but still can,t install any package in r-studio=server in rhel 7. Any help?
```
installing to /home/zillur/R/x86_64-redhat-linux-gnu-library/3.6/00LOCK-ndjson/00new/ndjson/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package ‘ndjson’
    finding HTML links ... done
    flatten                                 html  
    ndjson                                  html  
    stream_in                               html  
    validate                                html  
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘ndjson’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/zillur/R/x86_64-redhat-linux-gnu-library/3.6/00LOCK-ndjson/00new/ndjson/libs/ndjson.so':
  /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/zillur/R/x86_64-redhat-linux-gnu-library/3.6/00LOCK-ndjson/00new/ndjson/libs/ndjson.so)
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/zillur/R/x86_64-redhat-linux-gnu-library/3.6/ndjson’
Warning in install.packages :
  installation of package ‘ndjson’ had non-zero exit status
* installing *source* package ‘striprtf’ ...
** package ‘striprtf’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/home/zillur/R/x86_64-redhat-linux-gnu-library/3.6/Rcpp/include" -I/usr/local/include  -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c RcppExports.cpp -o RcppExports.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/home/zillur/R/x86_64-redhat-linux-gnu-library/3.6/Rcpp/include" -I/usr/local/include  -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c dechex.cpp -o dechex.o
dechex.cpp: In function ‘Rcpp::IntegerVector hex_to_int(std::string, char)’:
dechex.cpp:52:21: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::__cxx11::basic_string<char>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
   52 |   for (int i = 0; i < h.size(); i++)
      |                   ~~^~~~~~~~~~
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/home/zillur/R/x86_64-redhat-linux-gnu-library/3.6/Rcpp/include" -I/usr/local/include  -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c strip_helper.cpp -o strip_helper.o
g++ -m64 -std=gnu++11 -shared -L/usr/lib64/R/lib -Wl,-z,relro -o striprtf.so RcppExports.o dechex.o strip_helper.o -L/usr/lib64/R/lib -lR
installing to /home/zillur/R/x86_64-redhat-linux-gnu-library/3.6/00LOCK-striprtf/00new/striprtf/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package ‘striprtf’
    finding HTML links ... done
    looks_rtf                               html  
    read_rtf                                html  
    striprtf-deprecated                     html  
    unused_letters                          html  
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘striprtf’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/zillur/R/x86_64-redhat-linux-gnu-library/3.6/00LOCK-striprtf/00new/striprtf/libs/striprtf.so':
  /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/zillur/R/x86_64-redhat-linux-gnu-library/3.6/00LOCK-striprtf/00new/striprtf/libs/striprtf.so)
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/zillur/R/x86_64-redhat-linux-gnu-library/3.6/striprtf’
Warning in install.packages :
  installation of package ‘striprtf’ had non-zero exit status
ERROR: dependency ‘qpdf’ is not available for package ‘pdftools’
* removing ‘/home/zillur/R/x86_64-redhat-linux-gnu-library/3.6/pdftools’
Warning in install.packages :
  installation of package ‘pdftools’ had non-zero exit status
ERROR: dependencies ‘rjson’, ‘ndjson’ are not available for package ‘streamR’
* removing ‘/home/zillur/R/x86_64-redhat-linux-gnu-library/3.6/streamR’
Warning in install.packages :
  installation of package ‘streamR’ had non-zero exit status
ERROR: dependencies ‘pdftools’, ‘streamR’, ‘striprtf’ are not available for package ‘readtext’
* removing ‘/home/zillur/R/x86_64-redhat-linux-gnu-library/3.6/readtext’
Warning in install.packages :
  installation of package ‘readtext’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmp3LPz8i/downloaded_packages’
```

**Comment by jeroen** [comment]
curl 4.2 is on cran now.

**Comment by hanyunfan** [comment]
thanks a lot, @jeroen . Just tried, and it is working now.
